### ISSUE TITLE
Property :size is not working correctly

### ISSUE THREAD

**Issue by kaczor6418** [robcresswell/vue-material-design-icons#93] opened 2020-01-05 21:47 UTC
Property **:size** is not working because of width and height of ```.material-desig-cion > material-design-icon__svg```.

**Comment by kaczor6418** [comment] 2020-01-05 21:58
I created [PR: fix(size): size property #94](https://github.com/robcresswell/vue-material-design-icons/pull/94) which will fix this bug

**Comment by robcresswell** [comment] 2020-01-08 08:38
Hi @kaczor6418, thanks for raising an issue! This isn't a bug, I think. I recommend using the CSS *OR* the JS for styling, but not both. The CSS is optional, so you can write your own if you don't want to use the default; its only a few lines. Your fix will remove a lot of the default sizing from the CSS, which I disagree with.

See the note in https://github.com/robcresswell/vue-material-design-icons#props under `fillColor` about using one or the other. I'll update it for clarity

**Comment by kaczor6418** [comment] 2020-01-08 14:19
@robcresswell But in documentation I can read that I can use property :size to set size of icon but currently it is not possible
> ```size - This property overrides the `width` and `height` attributes on the
  SVG. The default is `24`. Example:
 <android-icon :size="48" />```

 to set size of icon but currently it is not possible. For example: 
```js
    <header>
      <menu-icon :size="100" />
      <search-web-icon :size="100" />
    </header>
```
so size of this ican should be 100 x 100, but it is not. Size of icon is still 24 x 24 which is default size of this icon. So in my opinion it is a bug

**Comment by kaczor6418** [comment] 2020-01-08 14:28
@robcresswell you do not have to use this css it is just my proposition. And i can say that you can do it even easier, you can remove whole ```.material-design-icon > .material-design-icon__svg``` class and center all icns in ```.material-design-icon``` class. Example below: 
```css
.material-design-icon {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
I do not see any benefits of this :
```css
.material-design-icon {
  display: inline-flex;
  align-self: center;
  position: relative;
  height: 1em;
  width: 1em;
}
.material-design-icon > .material-design-icon__svg {
  height: 1em;
  width: 1em;
  fill: currentColor;
  position: absolute;
  bottom: -0.125em;
}
```
If there is any please tell me. I am curious

**Comment by robcresswell** [comment] 2020-01-08 15:11
> so size of this ican should be 100 x 100, but it is not. Size of icon is still 24 x 24 which is default size of this icon. So in my opinion it is a bug

It's staying as 24 because the CSS is overruling it. If you remove the CSS like I suggested, it would work fine. As I said, its only an optional suggestion for people that don't like styling with JS (like myself)

>  you do not have to use this css it is just my proposition. And i can say that you can do it even easier, you can remove whole .material-design-icon > .material-design-icon__svg class and center all icns in .material-design-icon class

Cool! I'll take a look and see if it works

**Comment by kaczor6418** [comment] 2020-01-08 15:17
@robcresswell thank you for explanation, let me know is the code works

**Comment by rendomnet** [comment] 2020-04-02 11:24
this issue still exits

**Comment by Tardigrada777** [comment] 2020-04-17 13:13
@robcresswell 

it looks like the __viewBox__ is not changing because it is not dependent on __props.size__. Is it ok?

**Comment by altin-mapme** [comment] 2020-04-20 14:10
The size attribute is not working. The width and height of SVG are being set correctly but the size still remains at 24x24.

**Comment by kaczor6418** [comment] 2020-04-20 14:16
> @robcresswell you do not have to use this css it is just my proposition. And i can say that you can do it even easier, you can remove whole `.material-design-icon > .material-design-icon__svg` class and center all icns in `.material-design-icon` class. Example below:
> 
> ```css
> .material-design-icon {
>   display: flex;
>   align-items: center;
>   justify-content: center;
> }
> ```
> 
> I do not see any benefits of this :
> 
> ```css
> .material-design-icon {
>   display: inline-flex;
>   align-self: center;
>   position: relative;
>   height: 1em;
>   width: 1em;
> }
> .material-design-icon > .material-design-icon__svg {
>   height: 1em;
>   width: 1em;
>   fill: currentColor;
>   position: absolute;
>   bottom: -0.125em;
> }
> ```
> 
> If there is any please tell me. I am curious

@altin-mapme try this fix. You need change ```.css``` inside vue-material directory in node_modules directory. 

BTW I don't know why owner(@robcresswell) of this repository ignore my PR for such a long time. He said he will let me know is this change is acceptable, but he still didn't answer.

**Comment by Tardigrada777** [comment] 2020-04-20 17:32
@kaczor6418 

Thanks for your PR. I created a separate file with the styles that you suggested in your PR. 
Then I import the styles, not from node_modules, but mine. And it works fine. It strange that owner (@robcresswell) ignores your PR.

**Comment by altin-mapme** [comment] 2020-04-21 08:15
@kaczor6418 I don't think its a good idea to modify them in node_modules, as when the project gets to CI/CD pipelines, it will get the values from the original package. Your PR should be merged and the community shouldn't have to implement hacks to get around this. The package is used by over 1.5k projects, and as such it should have something as explicit as this working as intended.

**Comment by kaczor6418** [comment] 2020-04-21 12:41
> @kaczor6418 I don't think its a good idea to modify them in node_modules, as when the project gets to CI/CD pipelines, it will get the values from the original package. Your PR should be merged and the community shouldn't have to implement hacks to get around this. The package is used by over 1.5k projects, and as such it should have something as explicit as this working as intended.

@altin-mapme your are right. I just suggested work around, till PR will be merged

**Comment by robcresswell** [comment] 2020-05-27 17:11
Hey @kaczor6418, apologies for leaving this so. I don't do frontend work any more, so sitting down to figure this out involved setting some time aside. Anyway, here's a few screenshots from a default generated Nuxt project.

This is the current "suggested optional" CSS to help with scaling:

![before](https://user-images.githubusercontent.com/3816327/83050960-39bb8680-a045-11ea-95c5-1ed9fb1cbf26.png)

The icon scales to the surrounding text, and aligns fairly well too. If I change the size of the `<h2>`, then the icon scales appropriately.

If I try your changed CSS I get this:

![after](https://user-images.githubusercontent.com/3816327/83051099-696a8e80-a045-11ea-8aed-dab5ed5d9ed3.png)

This seems like a regression to me, unfortunately.

**Comment by robcresswell** [comment] 2020-05-27 17:14
@altin-mapme I'm not sure how to help you if you only say "its not working". My guess is that you've included the optional CSS, and then tried to set the size via JS as well, which won't work. Without CSS, and using the `size` prop, I get something like:

![size-prop](https://user-images.githubusercontent.com/3816327/83051628-2e1c8f80-a046-11ea-857b-834f0cdaa59c.png)

> The package is used by over 1.5k projects, and as such it should have something as explicit as this working as intended.

So yes, that seems to be working as intended. I will try and make the `README` more clear. If this is not the issue, please open a new issue for me to help with.

**Comment by robcresswell** [comment] 2020-07-13 12:59
Closing this now; if there's more to discuss, please comment again and I'll reopen. Thanks!

**Closed as completed** 2020-07-13 12:59 UTC
