### ISSUE TITLE
Vue3 issue

### ISSUE THREAD

**Issue by djcaesar9114** [robcresswell/vue-material-design-icons#262] opened 2021-01-19 20:38 UTC
Hello,
I followed exactly what is described in the README and I have this error in the console:

```
Uncaught (in promise) TypeError: Cannot read property 'decorative' of undefined
    at Proxy.render (Menu.vue?8aa8:2)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:710)
    at componentEffect (runtime-core.esm-bundler.js?5c40:4193)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:4176)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4134)
    at processComponent (runtime-core.esm-bundler.js?5c40:4094)
    at patch (runtime-core.esm-bundler.js?5c40:3712)
    at mountChildren (runtime-core.esm-bundler.js?5c40:3894)
```

**Comment by robcresswell** [comment] 2021-01-20 17:18
Duplicate of https://github.com/robcresswell/vue-material-design-icons/issues/230 really. I haven't got round to updating for Vue 3.

**Closed as completed** 2021-01-20 17:19 UTC
